version: "1"
maintainer: "https://github.com/tramchip/nifi/"
networks:
  default:
    driver: overlay

services:
  nifi:
    hostname :  nifi
    container_name: nifi
    image: apache/nifi:latest
    deploy:
      replicas: 1
    ports :
      - "9090:9090" #Nifi Web Application port 
      - 8443        #NiFi web application secure port
      - 8082        #NiFi ListenHTTP processor port
      - 2181        #zookeeper client port 
      - 2881        #NiFi site to site communication port
      - 2882        #NiFi cluster node protocol port
      - 2888        #Zookeeper port for monitoring NiFi nodes availability
      - 3888        #Zookeeper port for NiFi Cluster Coordinator election
      - 10000  #Nifi Site-to Site ports

      
    enviroment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      
    volumes:
      - type: bind
        source: "$(pwd)"/conf
        target: /opt/nifi/conf
      - type: bind
        source: "$(pwd)"/content_repository
        target: /dev/nvme1n1 /mnt/nifi_content
      - type: bind
        source: "$(pwd)"/database_repository
        target: /opt/nifi/database_repository
      - type: bind
        source: "$(pwd)"/flowfile_repository
        target: /opt/nifi/flowfile_repository
      - type: bind
        source: "$(pwd)"/provenance_repository
        target: /dev/nvme2n1 /mnt/nifi_prov
      - type: bind
        source: "$(pwd)"/logs
        target: /opt/nifi/logs
      - type: bind
        source: "$(pwd)"/data
        target: /opt/nifi/data
      

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  
    volumes :
      - type : bind
        source : ./path/to/zookeeper-persistence
        target : /opt/bitnami/zookeeper
      
  
