version: "1"
maintainer: "https://github.com/tramchip/nifi/"
services:
  nifi:
    hostname :  nifi
    container_name: nifi
    image: apache/nifi:latest
    deploy:
      replicas: 1
      
    enviroment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      
    volumes:
      - type: bind
        source: ./conf
        target: /opt/nifi/nifi-1.3.0/conf
      - type: bind
        source: ./content_repository
        target: /opt/nifi/nifi-1.3.0/content_repository
      - type: bind
        source: ./database_repository
        target: /opt/nifi/nifi-1.3.0/database_repository
      - type: bind
        source: ./flowfile_repository
        target: /opt/nifi/nifi-1.3.0/flowfile_repository
      - type: bind
        source: ./provenance_repository
        target: /opt/nifi/nifi-1.3.0/provenance_repository
      - type: bind
        source: ./logs
        target: /opt/nifi/nifi-1.3.0/logs
      - type: bind
        source: ./data
        target: /opt/nifi/nifi-1.3.0/data
      

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  
    volumes :
      - type : bind
        source : ./path/to/zookeeper-persistence
        target : /opt/bitnami/zookeeper
      
  
